// Generated by CoffeeScript 1.10.0
(function() {
  Polymer({
    is: "cordova-device",
    properties: {
      _promise: {
        type: Object,
        value: function() {
          return Q.defer();
        }
      },
      model: {
        notify: true,
        readOnly: true,
        reflectToAttribute: true,
        type: String
      },
      platform: {
        notify: true,
        readOnly: true,
        reflectToAttribute: true,
        type: String
      },
      ready: {
        notify: true,
        readOnly: true,
        reflectToAttribute: true,
        type: Boolean,
        value: false
      },
      uuid: {
        notify: true,
        readOnly: true,
        reflectToAttribute: true,
        type: String
      },
      version: {
        notify: true,
        readOnly: true,
        reflectToAttribute: true,
        type: String
      }
    },
    _onDeviceReady: function() {
      this._setReady(true);
      this._promise.resolve();
      this._setModel(device.model);
      this._setPlatform(device.platform);
      this._setUuid(device.uuid);
      return this._setVersion(device.version);
    },
    attached: function() {
      return window.addEventListener("deviceready", this._onDeviceReady.bind(this), false);
    },
    detached: function() {
      return window.removeEventListener("deviceready", this._onDeviceReady);
    },
    promise: function() {
      return this._promise.promise;
    }
  });

}).call(this);

//# sourceMappingURL=cordova-device.js.map
