// Generated by CoffeeScript 1.10.0
(function() {
  Polymer({
    is: "cordova-device",
    properties: {

      /* Return device model (Nexus One returns "Passion"). */
      model: {
        notify: true,
        readOnly: true,
        reflectToAttribute: true,
        type: String
      },

      /* Return device platform ("iOS"). */
      platform: {
        notify: true,
        readOnly: true,
        reflectToAttribute: true,
        type: String
      },

      /* Return if cordova deviceready event has been fired. */
      ready: {
        notify: true,
        readOnly: true,
        reflectToAttribute: true,
        type: Boolean,
        value: false
      },

      /* Return UUID created by manufacturer (BlackBerry returns the PIN number of
         the device).
       */
      uuid: {
        notify: true,
        readOnly: true,
        reflectToAttribute: true,
        type: String
      },

      /* Return device platform version (iOS 3.2 returns "3.2"). */
      version: {
        notify: true,
        readOnly: true,
        reflectToAttribute: true,
        type: String
      }
    },
    _onDeviceReady: function() {
      this._setModel(device.model);
      this._setPlatform(device.platform);
      this._setReady(true);
      this._setUuid(device.uuid);
      return this._setVersion(device.version);
    },
    attached: function() {
      return document.addEventListener("deviceready", this._onDeviceReady.bind(this), false);
    },
    detached: function() {
      return document.removeEventListener("deviceready", this._onDeviceReady);
    }
  });

}).call(this);

//# sourceMappingURL=cordova-device.js.map
